# Generated by Django 2.2.6 on 2019-11-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191114_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This ai our product,quality and good'),
            preserve_default=False,
        ),
    ]
