# Generated by Django 2.2.6 on 2019-11-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20191119_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='item.jpg', upload_to='item_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='item.jpg', upload_to='item_images'),
        ),
    ]
